Repository typeorm/typeorm, pull requests merged in 2022-02, with the labels that each got.

#8613 docs: put proper documentation for Not operator
  src/find-options/operator/Not.ts
Labels: documentation

#8581 fix: mongodb repository.find filters soft deleted rows
  src/entity-manager/MongoEntityManager.ts
  test/github-issues/7113/entity/Configuration.ts
  test/github-issues/7113/issue-7113.ts
  test/github-issues/7113/repository/ConfigurationRepository.ts
Labels: driver: mongodb

#8403 feat: Separate update event into the update, soft remove and recover events
  docs/decorator-reference.md
  docs/listeners-and-subscribers.md
  docs/zh_CN/decorator-reference.md
  docs/zh_CN/listeners-and-subscribers.md
  extra/typeorm-class-transformer-shim.js
  extra/typeorm-model-shim.js
  sample/sample5-subscribers/subscriber/EverythingSubscriber.ts
  sample/sample9-entity-listeners/entity/Post.ts
  sample/sample9-entity-listeners/entity/PostAuthor.ts
  sample/sample9-entity-listeners/entity/PostCategory.ts
  src/decorator/listeners/AfterRecover.ts
  src/decorator/listeners/AfterSoftRemove.ts
  src/decorator/listeners/BeforeRecover.ts
  src/decorator/listeners/BeforeSoftRemove.ts
  src/index.ts
  src/metadata-builder/EntityMetadataBuilder.ts
  src/metadata/EntityMetadata.ts
  src/metadata/types/EventListenerTypes.ts
  src/persistence/SubjectExecutor.ts
  src/query-builder/SoftDeleteQueryBuilder.ts
  src/subscriber/Broadcaster.ts
  src/subscriber/EntitySubscriberInterface.ts
  src/subscriber/event/RecoverEvent.ts
  src/subscriber/event/SoftRemoveEvent.ts
  test/functional/persistence/persistence-options/listeners/entity/PostWithDeleteDateColumn.ts
  test/github-issues/6327/subscriber/PostSubscriber.ts
  test/github-issues/8398/entity/Post.ts
  test/github-issues/8398/issue-8398.ts
  test/github-issues/8398/subscriber/PostSubscriber.ts
Labels: breaking change

#7432 fix: prefix relation id columns contained in embedded entities (#6977)
  src/metadata-builder/RelationJoinColumnBuilder.ts
  test/functional/entity-metadata/entity/Counters.ts
  test/functional/metadata-builder/column-metadata/entity/Counters.ts
  test/functional/query-builder/relation-id/many-to-many/embedded-with-multiple-pk/entity/Counters.ts
  test/functional/query-builder/relation-id/many-to-one/embedded-with-multiple-pk/entity/Counters.ts
  test/functional/query-builder/relation-id/many-to-one/embedded/entity/Counters.ts
  test/functional/query-builder/relation-id/one-to-many/embedded-with-multiple-pk/entity/Counters.ts
  test/functional/query-builder/relation-id/one-to-many/embedded/entity/Counters.ts
  test/functional/query-builder/relation-id/one-to-one/embedded-with-multiple-pk/entity/Counters.ts
  test/functional/query-builder/relation-id/one-to-one/embedded/entity/Counters.ts
  test/github-issues/6977/entity/Embedded.ts
  test/github-issues/6977/entity/User.ts
  test/github-issues/6977/issue-6977.ts
Labels: breaking change

#7538 fix: find by Date object in sqlite driver
  src/driver/sqlite-abstract/AbstractSqliteDriver.ts
  test/github-issues/2286/entity/Example.ts
  test/github-issues/2286/entity/Post.ts
  test/github-issues/2286/issue-2286.ts
Labels: breaking change

#6104 Implement deferrable foreign keys for SAP HANA
  src/driver/sap/SapQueryRunner.ts
Labels: needs tests
