Repository typeorm/typeorm, pull requests merged in 2025-04, with the labels that each got.

#10809 fix: remove unnecessary spaces in message when running non-fake migrations
  src/migration/MigrationExecutor.ts
Labels: size-xs

#11107 feat: Support Expo SQLite Next
  src/driver/DriverFactory.ts
  src/driver/expo/ExpoDriver.ts
  src/driver/expo/ExpoDriverFactory.ts
  src/driver/expo/ExpoQueryRunner.ts
  src/driver/expo/legacy/ExpoLegacyDriver.ts
  src/driver/expo/legacy/ExpoLegacyQueryRunner.ts
Labels: driver: expo

#11144 feat: add new foreign key decorator, and entity schemas options
  docs/decorator-reference.md
  docs/separating-entity-definition.md
  extra/typeorm-model-shim.js
  sample/sample35-foreign-keys/app.ts
  sample/sample35-foreign-keys/entity/city.ts
  sample/sample35-foreign-keys/entity/country.ts
  sample/sample35-foreign-keys/entity/order.ts
  sample/sample35-foreign-keys/entity/user.ts
  sample/sample36-schemas-foreign-keys/app.ts
  sample/sample36-schemas-foreign-keys/entity/city.ts
  sample/sample36-schemas-foreign-keys/entity/country.ts
  sample/sample36-schemas-foreign-keys/entity/order.ts
  sample/sample36-schemas-foreign-keys/entity/user.ts
  sample/sample36-schemas-foreign-keys/model/city.ts
  sample/sample36-schemas-foreign-keys/model/country.ts
  sample/sample36-schemas-foreign-keys/model/order.ts
  sample/sample36-schemas-foreign-keys/model/user.ts
  src/decorator/ForeignKey.ts
  src/decorator/options/ForeignKeyOptions.ts
  src/entity-schema/EntitySchemaColumnForeignKeyOptions.ts
  src/entity-schema/EntitySchemaColumnOptions.ts
  src/entity-schema/EntitySchemaForeignKeyOptions.ts
  src/entity-schema/EntitySchemaOptions.ts
  src/entity-schema/EntitySchemaTransformer.ts
  src/index.ts
  src/metadata-args/ForeignKeyMetadataArgs.ts
  src/metadata-args/MetadataArgsStorage.ts
  src/metadata-builder/EntityMetadataBuilder.ts
  test/functional/decorators/foreign-key/entity/city.ts
  test/functional/decorators/foreign-key/entity/country.ts
  test/functional/decorators/foreign-key/entity/order.ts
  test/functional/decorators/foreign-key/entity/user.ts
  test/functional/decorators/foreign-key/foreign-key-decorator.ts
  test/functional/decorators/foreign-key/wrong-city.ts
  test/functional/entity-schema/foreign-keys/entity/city.ts
  test/functional/entity-schema/foreign-keys/entity/country.ts
  test/functional/entity-schema/foreign-keys/entity/order.ts
  test/functional/entity-schema/foreign-keys/entity/user.ts
  test/functional/entity-schema/foreign-keys/foreign-keys-basic.ts
  test/functional/entity-schema/foreign-keys/model/city.ts
  test/functional/entity-schema/foreign-keys/model/country.ts
  test/functional/entity-schema/foreign-keys/model/order.ts
  test/functional/entity-schema/foreign-keys/model/user.ts
Labels: new feature, comp: entity schemas, need review help, complexity: medium

#10846 feat: Add query timeout support for MySql
  docs/data-source-options.md
  src/driver/mysql/MysqlConnectionOptions.ts
  src/driver/mysql/MysqlQueryRunner.ts
  test/functional/driver/mysql/connection-options/enable-query-timeout.ts
Labels: new feature, driver: mariadb, driver: mssql, size-s

#10754 Propagate `aggregate` method's generic parameter to its returned cursor
  src/repository/MongoRepository.ts
Labels: size-xs

#11259 refactor: define Position type for GeoJSON objects
  src/driver/types/GeoJsonTypes.ts
Labels: breaking change, size-xs

#11282 docs: update repository additional chunk option usage example
  docs/repository-api.md
Labels: documentation
